FilmCourseWebApp/Models/Category.cs
namespace FilmCourseWebApp.Models
{
    public class Category
    {
        public int Id { get; set; }
        public string Name { get; set; }
    }
}

FilmCourseWebApp/Models/ErrorViewModel.cs
namespace FilmCourseWebApp.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

FilmCourseWebApp/Models/Movie.cs
namespace FilmCourseWebApp.Models
{
    public class Movie
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string ShortDescription { get; set; }
        public string Description { get; set; }
        public string ImageUrl { get; set; }

        public int CategoryId { get; set; }
    }
}

FilmCourseWebApp/Models/MovieCategoryModel.cs
namespace FilmCourseWebApp.Models
{
    public class MovieCategoryModel
    {
        public IEnumerable<Movie> Movies{ get; set; }
        public IEnumerable<Category> Categories{ get; set; }

        public Movie Movie { get; set; }
    }
}

FilmCourseWebApp/Controllers/HomeController.cs
using FilmCourseWebApp.Data;
using FilmCourseWebApp.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace FilmCourseWebApp.Controllers
{
    public class HomeController : Controller
    {
       
       public IActionResult Index(int ?id)
        {
            var movies = MovieRepository.Movies;
            if(id != null)
            {
                movies = movies.Where(i => i.CategoryId == id).ToList();
            }

            return View(movies);
        }
        public IActionResult Details(int id)
        {
            //MovieCategoryModel model = new MovieCategoryModel();
            //model.Categories = CategoryRepository.Categories;
            //model.Movie = MovieRepository.GetById(id);
            return View(MovieRepository.GetById(id));
        }

        public IActionResult Contact()
        {
            return View();
        }
    }
}

FilmCourseWebApp/Controllers/MovieController.cs
using Microsoft.AspNetCore.Mvc;

namespace FilmCourseWebApp.Controllers
{
    public class MovieController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
        public IActionResult Create()
        {
            return View();
        }
        public IActionResult List()
        {
            return View();
        }
        public IActionResult Details()
        {
            return View();
        }
    }
}

FilmCourseWebApp/ViewComponents/CategoryMenuViewComponent.cs
using FilmCourseWebApp.Data;
using Microsoft.AspNetCore.Mvc;

namespace FilmCourseWebApp.ViewComponents
{
    public class CategoryMenuViewComponent : ViewComponent
    {
        public IViewComponentResult Invoke()
        {
            if(RouteData.Values["action"].ToString() == "Index")
            ViewBag.SelectedCategory = RouteData?.Values["id"];
            return View(CategoryRepository.Categories);
        }
    }
}

FilmCourseWebApp/Views/Home/Contact.cshtml
<h1>Home/Contact</h1>

FilmCourseWebApp/Views/Home/Details.cshtml
@model Movie
<div class="row">
	<div class="col-md-3">
		@*@Html.Partial("_menu", Model.Categories)*@
		@await Component.InvokeAsync("CategoryMenu")
	</div>
	<div class="col-md-9">

		<div class="card mb-3">
			<div class="card-body">
				<div class="row no-gutter">

					<div class="col md-4">
						<img src="~/img/@Model.ImageUrl" alt="@Model.Description" class="card-img" />
					</div>
					<div class="col md-8">

						<h5 class="card-title">
							@*<a href="/home/details/@movie.Id">	@movie.Name </a>*@
							<a asp-action="Details" asp-controller="Home" asp-route-id="@Model.Id"> @Model.Name </a>
						</h5>
						<p class="card-text">@Model.Description</p>
						<p class="card-text">
							<small class="text-muted">3 days ago</small>
						</p>

					</div>

				</div>
			</div>



		</div>

	</div>
</div>

FilmCourseWebApp/Views/Home/Index.cshtml
@model IEnumerable<Movie>
<div class="row">
	<div class="col-md-3">
		@*@Html.Partial("_menu", Model.Categories)*@
		@await Component.InvokeAsync("CategoryMenu")
	</div>
	<div class="col-md-9">
		@Html.Partial("_movies", Model)
		@*<partial name="_movies" model="Model.Movies"></partial>*@
	</div>
</div>

FilmCourseWebApp/Views/Home/_movies.cshtml
@model IEnumerable<Movie>

@foreach(var movie in Model)
{<div class="card mb-3">
	<div class="row no-gutter">
		<div class="col md-3">
			<img src="~/img/@movie.ImageUrl" alt="@movie.Description" class="card-img"/>
		</div>
		<div class="col md-9">
			<div class="card-body">
				<h5 class="card-title">
				@*<a href="/home/details/@movie.Id">	@movie.Name </a>*@
				<a asp-action="Details" asp-controller="Home" asp-route-id="@movie.Id"> @movie.Name </a>
					</h5>
				<p class="card-text">@movie.Description</p>
				<p class="card-text">
					<small class="text-muted">3 days ago</small>
				</p>
			</div>
	</div>
</div>
</div>
}

FilmCourseWebApp/Views/Movie/Details.cshtml
<h1>Movie/Details</h1>

FilmCourseWebApp/Views/Movie/Index.cshtml
<h1>Movie/Index</h1>

FilmCourseWebApp/Views/Movie/List.cshtml
<h1>Movie/List</h1>

FilmCourseWebApp/Views/Shared/Components/CategoryMenu/Default.cshtml
@model IEnumerable<Category>
<div class="list-group">
	<a href="/" class="list-group-item list-group-item-action">
		All Categories
	</a>
	@foreach(var i in Model)
	{
		<a asp-controller="Home" asp-action="Index" asp-route-id="@i.Id" 
		class="list-group-item list-group-item-action @(ViewBag.SelectedCategory
			== i.Id.ToString()? "active":"")">
		@i.Name</a>
	}
	</div>

FilmCourseWebApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - FilmCourseWebApp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/FilmCourseWebApp.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        @Html.Partial("_navbar")
        </header>
    <main>
        <div class="container mt-4">
               @RenderBody()
        </div>
    </main>
    <footer>
        @Html.Partial("_footer")
    </footer>
 
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

FilmCourseWebApp/Views/Shared/_footer.cshtml
<div class="footer py-3 mt-3">
	<div class="container">
		<span class="text-muted">
			Place footer content here
		</span>
		</div>

</div>

FilmCourseWebApp/Views/Shared/_menu.cshtml
@model IEnumerable<Category>
<div class="list-group">
	@foreach(var i in Model)
	{
		<a href='#' class="list-group-item list-group-item-action">@i.Name</a>
	}
	</div>




@*<div class="list-group">
	<a href='#' class="list-group-item list-group-item-action active">Link Item 1</a>
	<a href='#' class="list-group-item list-group-item-action action">Link Item 2</a>
	<a href='#' class="list-group-item list-group-item-action action">Link Item 3</a>
	<a href='#' class="list-group-item list-group-item-action action">Link Item 4</a>
	<a href='#' class="list-group-item list-group-item-action action">Link Item 5</a>
</div>*@

FilmCourseWebApp/Views/Shared/_navbar.cshtml
<div class="navbar navbar-expand-sm bg-primary navbar-dark">
	<div class="container">
		<a href="/" class="navbar-brand">Movie App</a>
		<ul class="navbar-nav">
			<li class="nav-item">
				<a href="/login" class="nav-link">Login</a>
			</li>
			<li class="nav-item">
				<a href="/register" class="nav-link">Register</a>
			</li>
		</ul>
	</div>
</div>